// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhojgwjijciwcgiudmcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZob2pnd2ppamNpd2NnaXVkbWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTU4MzYsImV4cCI6MjA1OTM3MTgzNn0.ZZX2US4FkzgM-G73DO5o9zUKqWZE2dtk00qyeMnauF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);